name: 'json-schema-validation'
description: 'Validates that a set of JSON objects conforms to the defined schema'
inputs:
  schema:
    description: 'The filename of the JSON schema'
    required: true
  testFile:
    description: 'The filename of the JSON test file'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
